<?php

$_order = $this->getBliskaOrder();
/* @var $senditHelper Sendit_Bliskapaczka_Helper_Data */
$senditHelper =Mage::helper('sendit_bliskapaczka');
/* @var $senditTrackingHelper Sendit_Bliskapaczka_Helper_Tracking */
$senditTrackingHelper = Mage::helper('sendit_bliskapaczka/tracking');
?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Bliskapaczka order info') ?></h4>
    </div>
    <fieldset>
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Number') ?></label></td>
                <td class="value"><strong><?php echo ($_order->getNumber() ?: '-') ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Status') ?></label></td>
                <td class="value"><strong><?php echo ($_order->getStatus() ?: '-') ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Delivery type') ?></label></td>
                <td class="value"><strong><?php echo ($_order->getDeliveryType() ?: '-') ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Creation date') ?></label></td>
                <td class="value"><strong><?php echo ($_order->getCreationDate() ?: '-') ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Operator Name') ?></label></td>
                <td class="value"><strong><?php echo ($_order->getPosOperator() ?: '-') ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Destination Code') ?></label></td>
                <td class="value"><strong><?php echo ($_order->getPosCode() ?: '-') ?></strong></td>
            </tr>
            <tr>
                <td class="label">
                    <label>
                        <?php echo Mage::helper('sales')->__('Destination Point Description') ?>
                    </label>
                </td>
                <td class="value"><strong><?php echo ($_order->getPosCodeDescription() ?: '-') ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Advice date') ?></label></td>
                <td class="value"><strong><?php echo ($_order->getAdviceDate() ?: '-') ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Tracking number') ?></label></td>
                <td class="value"><strong><?php echo ($_order->getTrackingNumber() ?: '-') ?></strong></td>
            </tr>
            <?php if ($_order->getTrackingNumber()): ?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Tracking link') ?></label></td>
                    <td class="value"><a href="<?php echo $senditTrackingHelper->getLink($_order->getTrackingNumber(), $senditHelper); ?>"><?php echo $senditTrackingHelper->getLink($_order->getTrackingNumber(), $senditHelper); ?></a></td>
                </tr>
            <?php endif; ?>
        </table>
    </fieldset>
</div>
