#!/bin/bash

function info {
    printf "\033[0;36m===> \033[0;33m${1}\033[0m\n"
}

service cron start

service php5-fpm start

service nginx start

MAGENTO_PATH=/var/www/magento

info "Configure Magento"
sed -i -e "s/DB_HOST/$DB_HOST/g" $MAGENTO_PATH/app/etc/local.xml
sed -i -e "s/DB_USER/$MYSQL_USER/g" $MAGENTO_PATH/app/etc/local.xml
sed -i -e "s/DB_PASS/$MYSQL_PASSWORD/g" $MAGENTO_PATH/app/etc/local.xml
sed -i -e "s/DB_NAME/$MYSQL_DATABASE/g" $MAGENTO_PATH/app/etc/local.xml

info "Sleep 10s, waiting for mysql "
sleep 10

if [ $(mysql -N -s -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -e "select count(*) from information_schema.tables where table_schema='$MYSQL_DATABASE' and table_name='core_config_data';") -eq 1 ]; then
    info "Nothing to do"
else
	info "Import Magento Sample Data"
    mysql -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < $MAGENTO_PATH/magento_sample_data_for_1.9.2.4.sql
	mysql -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e 'UPDATE `core_resource` SET version = "1.6.2.0.5", data_version = "1.6.2.0.5" WHERE code = "customer_setup";'
	mysql -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e 'INSERT INTO `admin_user` (firstname, lastname, email, username, password, created, lognum, reload_acl_flag, is_active, rp_token_created_at) VALUES ("Admin", "Admin", "admin@example.com", "admin", "482c811da5d5b4bc6d497ffa98491e38", NOW(), 0, 0, 1, NOW());'
	mysql -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e 'INSERT INTO `admin_role` (parent_id,tree_level,sort_order,role_type,user_id,role_name) VALUES (1,2,0,"U",(SELECT user_id FROM admin_user WHERE username = "admin"),"Admin");'

	mysql -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e 'UPDATE `core_config_data` SET value = "pl_PL" WHERE path = "general/locale/code" AND scope = "default";'
	mysql -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e 'UPDATE `core_config_data` SET value = "PL" WHERE path = "general/country/default" AND scope = "default";'
	mysql -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e 'UPDATE `core_store` SET name = "Polski" WHERE code = "default";'
fi

while true; do
echo "Everything fine"
sleep 3600
done
